# Generated by Django 3.0.5 on 2020-05-14 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200512_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='answerreview',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_like_key', to='main_app.Answer'),
        ),
        migrations.AlterField(
            model_name='answerreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_like_key', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='answerreview',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='uniqueAnswerReview'),
        ),
    ]
