# Generated by Django 3.0.5 on 2020-05-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200514_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='accepted',
        ),
        migrations.AddField(
            model_name='question',
            name='accepted_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_answer', to='main_app.Answer'),
        ),
    ]
