# Generated by Django 3.0.5 on 2020-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200516_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
