# Generated by Django 3.0.5 on 2020-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_group_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='field_name',
            field=models.CharField(choices=[('Matematika', 'Mat'), ('Fizika', 'Fiz'), ('Kemija', 'Kem'), ('Biologija', 'Bio'), ('Arhitektura', 'Arh'), ('Brodogradnja', 'Brod'), ('Elektrotehnika', 'Et'), ('Građevinarstvo', 'Grad'), ('Kemijsko inženjerstvo', 'Kem Inz'), ('Računarstvo', 'Rac'), ('Strojarstvo', 'Str'), ('Tehnologija prometa', 'Teh Prom'), ('Medicina', 'Med'), ('Veterina', 'Vet'), ('Dentalna medicina', 'Dent'), ('Farmacija', 'Farm'), ('Biotehnologija', 'Bt'), ('Prehrambena tehnologija', 'Pt')], max_length=50),
        ),
    ]
