# Generated by Django 3.0.5 on 2020-07-28 18:02

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200720_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=main_app.models.update_filename, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=main_app.models.update_filename, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, upload_to=main_app.models.update_filename, verbose_name=''),
        ),
    ]
